# Generated by Django 4.0 on 2023-06-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default=1, max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('email',), name='one_row_per_email'),
        ),
    ]
