# Generated by Django 4.0 on 2023-06-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_remove_subscriber_id_remove_subscriber_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='epoch',
            field=models.DateField(auto_now=True),
        ),
    ]
