# Generated by Django 4.0 on 2023-06-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product', '0005_product_stripe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('a', 'Endurance'), ('b', 'Powerlifting'), ('c', 'Spin Indoor Cycling'), ('d', 'Flexibility')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('user_id', 'day', 'time', 'type'), name='one_class_per_slot_per_user'),
        ),
    ]
