# Generated by Django 4.0 on 2023-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_workout_workout_one_class_per_slot_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['day', 'time']},
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.CharField(choices=[('01', '1am'), ('02', '2am'), ('03', '3am'), ('04', '4am'), ('05', '5am'), ('06', '6am'), ('07', '7am'), ('08', '8am'), ('09', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('13', '1pm'), ('14', '2pm'), ('15', '3pm'), ('16', '4pm'), ('17', '5pm'), ('18', '6pm'), ('19', '7pm'), ('20', '8pm'), ('21', '9pm'), ('22', '10pm'), ('23', '11pm'), ('24', '12am')], max_length=2),
        ),
    ]
