# Generated by Django 4.0 on 2023-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_workout_options_alter_workout_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workout',
            name='one_class_per_slot_per_user',
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('user_id', 'day', 'time'), name='one_class_per_slot_per_user'),
        ),
    ]
