# Generated by Django 4.0 on 2023-06-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='recurring',
        ),
    ]
