# Generated by Django 4.0 on 2023-06-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_membership_recurring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
